### ISSUE TITLE
ClassCastException in Vert.x Pump (RxJava2)

### ISSUE THREAD

**Issue by Jotschi** [vert-x3/vertx-rx#123]
### Version

* vert.x core: 3.5.0
* vert.x rxjava2: 3.5.0

### Context

I encountered an exception which looks suspicious while using the Vert.x Pump (RxJava2 variant)

### Do you have a reproducer?

https://gist.github.com/Jotschi/76ba42e7dc66a4a280b1323599152364

### Stacktrace

```
java.lang.ClassCastException: io.vertx.reactivex.core.buffer.Buffer cannot be cast to io.vertx.core.buffer.Buffer
	at io.vertx.core.file.impl.AsyncFileImpl.write(AsyncFileImpl.java:57)
	at io.vertx.core.streams.impl.PumpImpl.lambda$new$1(PumpImpl.java:64)
	at io.vertx.reactivex.core.impl.ReadStreamSubscriber.checkStatus(ReadStreamSubscriber.java:141)
	at io.vertx.reactivex.core.impl.ReadStreamSubscriber.onNext(ReadStreamSubscriber.java:195)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.drain(FlowableOnBackpressureBuffer.java:187)
	at io.reactivex.internal.operators.flowable.FlowableOnBackpressureBuffer$BackpressureBufferSubscriber.request(FlowableOnBackpressureBuffer.java:142)
	at io.reactivex.internal.subscriptions.SubscriptionHelper.deferredRequest(SubscriptionHelper.java:227)
	at io.reactivex.internal.subscribers.StrictSubscriber.request(StrictSubscriber.java:70)
	at io.vertx.reactivex.core.impl.ReadStreamSubscriber.lambda$checkStatus$2(ReadStreamSubscriber.java:135)
	at io.vertx.reactivex.core.impl.ReadStreamSubscriber.checkStatus(ReadStreamSubscriber.java:143)
	at io.vertx.reactivex.core.impl.ReadStreamSubscriber.handler(ReadStreamSubscriber.java:67)
	at io.vertx.core.streams.impl.PumpImpl.start(PumpImpl.java:87)
	at io.vertx.core.streams.impl.PumpImpl.start(PumpImpl.java:42)
	at io.vertx.reactivex.core.streams.Pump.start(Pump.java:173)
	at com.gentics.mesh.storage.PumpTest.lambda$0(PumpTest.java:32)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.vertx.reactivex.core.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:41)
	at io.vertx.reactivex.core.file.FileSystem$4.handle(FileSystem.java:1071)
	at io.vertx.reactivex.core.file.FileSystem$4.handle(FileSystem.java:1068)
	at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:81)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:294)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:344)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:463)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:748)
```

## Workaround

	/**
	 * Creates a pump which applies a workaround for vertx-rxjava#123.
	 * 
	 * @param stream
	 * @param file
	 * @return
	 */
	public static Pump pump(Observable<Buffer> stream, AsyncFile file) {
		ReadStream<io.vertx.core.buffer.Buffer> rss = ReadStreamSubscriber.asReadStream(stream.map(Buffer::getDelegate), Function.identity());
		io.vertx.core.streams.Pump pump = io.vertx.core.streams.Pump.pump(rss, file.getDelegate());
		return Pump.newInstance(pump);
	}

**Comment by vietj** [comment]
I believe that's something we cannot really fix and it is due to the fact that generics are not reified.

Actually I believe that in this situation one should not create a Pump from a Flowable but rather turn a WriteStream intro an Observer : https://github.com/vert-x3/vertx-rx/issues/115

**Comment by tsegismont** [comment]
@Jotschi closing this one as `wontfix` as per @vietj 's comment above.

A PR has just been merged in master for #115 and backported to 3.6.1. So this should work to solve your problem:

```java
    Observable<Buffer> rs = Observable.just(Buffer.buffer("test123"));
    vertx.fileSystem().rxOpen(file.getAbsolutePath(), new OpenOptions()).flatMapCompletable(asyncFile -> {
      return Completable.create(emitter -> {
        rs.subscribe(asyncFile.toObserver().onComplete(() -> emitter.onComplete()));
      });
    }).blockingAwait();
```

**Comment by bentatham** [comment]
I have the same ClassCastException when using Pump with a `io.vertx.reactivex.core.http.HttpServerResponse` and a `Flowable<io.vertx.reactivex.core.buffer.Buffer>`.

`Pump.pump(flowable, response).start()`.

This is with vertx 3.6.3 and rxjava 2.2.5.

Any thoughts on a work around?  This seems like it should work from an API perspective.

**Comment by vietj** [comment]
can you try with 3.7 ?

**Comment by bentatham** [comment]
Yep - just tried it -- Fails with the latest vertx 3.7.0 / rxjava 2.2.8 as well.

```
java.lang.ClassCastException: class io.vertx.reactivex.core.buffer.Buffer cannot be cast to class io.vertx.core.buffer.Buffer (io.vertx.reactivex.core.buffer.Buffer and io.vertx.core.buffer.Buffer are in unnamed module of loader 'app')
	at io.vertx.core.http.impl.HttpServerResponseImpl.write(HttpServerResponseImpl.java:54)
	at io.vertx.core.streams.impl.PumpImpl.lambda$new$1(PumpImpl.java:59)
	at io.vertx.reactivex.impl.ReadStreamSubscriber.checkStatus(ReadStreamSubscriber.java:146)
	at io.vertx.reactivex.impl.ReadStreamSubscriber.onNext(ReadStreamSubscriber.java:200)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.reactivex.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onNext(FlowableDoOnEach.java:92)
...
```

**Comment by bentatham** [comment]
The same workaround as in the original description works for me, but not rxjava :(

```
io.vertx.core.streams.Pump.pump(ReadStreamSubscriber.asReadStream(flowable, Buffer::getDelegate), response.getDelegate()).start();
```

**Comment by tsegismont** [comment]
@bentatham I believe @vietj meant to try this: https://github.com/vert-x3/vertx-rx/issues/123#issuecomment-446557830

See #115
