### ISSUE TITLE
ReadStreamSubscriber does not preserve order

### ISSUE THREAD

**Issue by tsegismont** [vert-x3/vertx-rx#126]
The `ReadStream` you get from a `Flowable` with `ReadStreamSubscriber#asReadStream`  does not preserver order of elements.

Consider the following test:

```java
package io.vertx.reactivex.test;

import io.reactivex.Flowable;
import io.vertx.core.Vertx;
import io.vertx.core.buffer.Buffer;
import io.vertx.core.file.AsyncFile;
import io.vertx.core.file.OpenOptions;
import io.vertx.core.streams.Pump;
import io.vertx.core.streams.ReadStream;
import io.vertx.reactivex.core.impl.ReadStreamSubscriber;
import io.vertx.test.core.Repeat;
import io.vertx.test.core.RepeatRule;
import io.vertx.test.core.TestUtils;
import org.junit.After;
import org.junit.Before;
import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;

import java.io.ByteArrayInputStream;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;

import static org.junit.Assert.*;

public class ReadStreamSubscriberBugTest {

  @Rule
  public RepeatRule repeat = new RepeatRule();
  @Rule
  public TemporaryFolder temporaryFolder = new TemporaryFolder();

  private Vertx vertx;
  private byte[] content;

  @Before
  public void setUp() throws Exception {
    vertx = Vertx.vertx();
    Path testFile = temporaryFolder.newFile().toPath();
    content = TestUtils.randomByteArray(1024 * 1024); // big enough not to fit into stream queues
    Files.write(testFile, content);
  }

  @After
  public void tearDown() {
    vertx.close();
  }

  @Test
  @Repeat(times = 100)
  public void httpRequestToFile() throws Exception {
    File destFile = temporaryFolder.newFile();

    AsyncFile asyncFile = vertx.fileSystem().openBlocking(destFile.getPath(), new OpenOptions());

    Flowable<Buffer> source = Flowable.using(() -> new ByteArrayInputStream(content), bais -> {
      return Flowable.generate(emitter -> {
        byte[] bytes = new byte[1024 * 100];
        int read = bais.read(bytes);
        if (read == -1) {
          emitter.onComplete();
          return;
        }
        emitter.onNext(Buffer.buffer(read).appendBytes(bytes, 0, read));
      });
    }, ByteArrayInputStream::close);

    CountDownLatch latch = new CountDownLatch(1);
    ReadStream<Buffer> readStream = ReadStreamSubscriber.asReadStream(source, Function.identity());
    readStream.endHandler(v -> asyncFile.flush(f -> asyncFile.close(c -> latch.countDown())));
    Pump.pump(readStream, asyncFile).start();
    latch.await(1, TimeUnit.MINUTES);

    assertArrayEquals("Content differs", content, Files.readAllBytes(destFile.toPath()));
  }
}

```

It fails with:

```
/usr/lib/jvm/java-1.8.0-openjdk/bin/java -ea -Dio.netty.leakDetectionLevel=PARANOID -Didea.test.cyclic.buffer.size=1048576 -javaagent:/home/tsegismont/Tools/idea-IU/lib/idea_rt.jar=46433:/home/tsegismont/Tools/idea-IU/bin -Dfile.encoding=UTF-8 -classpath /home/tsegismont/Tools/idea-IU/lib/idea_rt.jar:/home/tsegismont/Tools/idea-IU/plugins/junit/lib/junit-rt.jar:/home/tsegismont/Tools/idea-IU/plugins/junit/lib/junit5-rt.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/rt.jar:/home/tsegismont/Projets/vert-x3/vertx-rx/rx-java2/target/test-classes:/home/tsegismont/Projets/vert-x3/vertx-rx/rx-java2/target/classes:/home/tsegismont/mavenrepo/io/reactivex/rxjava2/rxjava/2.1.3/rxjava-2.1.3.jar:/home/tsegismont/mavenrepo/org/reactivestreams/reactive-streams/1.0.1/reactive-streams-1.0.1.jar:/home/tsegismont/mavenrepo/io/vertx/vertx-core/3.5.1-SNAPSHOT/vertx-core-3.5.1-20180118.075439-95.jar:/home/tsegismont/mavenrepo/io/netty/netty-common/4.1.19.Final/netty-common-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-buffer/4.1.19.Final/netty-buffer-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-transport/4.1.19.Final/netty-transport-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-handler/4.1.19.Final/netty-handler-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-codec/4.1.19.Final/netty-codec-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-handler-proxy/4.1.19.Final/netty-handler-proxy-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-codec-socks/4.1.19.Final/netty-codec-socks-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-codec-http/4.1.19.Final/netty-codec-http-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-codec-http2/4.1.19.Final/netty-codec-http2-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-resolver/4.1.19.Final/netty-resolver-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-resolver-dns/4.1.19.Final/netty-resolver-dns-4.1.19.Final.jar:/home/tsegismont/mavenrepo/io/netty/netty-codec-dns/4.1.19.Final/netty-codec-dns-4.1.19.Final.jar:/home/tsegismont/mavenrepo/com/fasterxml/jackson/core/jackson-core/2.9.3/jackson-core-2.9.3.jar:/home/tsegismont/mavenrepo/com/fasterxml/jackson/core/jackson-databind/2.9.3/jackson-databind-2.9.3.jar:/home/tsegismont/mavenrepo/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/home/tsegismont/mavenrepo/io/vertx/vertx-codegen/3.5.1-SNAPSHOT/vertx-codegen-3.5.1-20180118.074517-10.jar:/home/tsegismont/mavenrepo/org/mvel/mvel2/2.3.1.Final/mvel2-2.3.1.Final.jar:/home/tsegismont/mavenrepo/io/vertx/vertx-docgen/3.5.1-SNAPSHOT/vertx-docgen-3.5.1-20180118.080927-4.jar:/home/tsegismont/mavenrepo/io/vertx/vertx-core/3.5.1-SNAPSHOT/vertx-core-3.5.1-20180118.075439-95-sources.jar:/home/tsegismont/mavenrepo/io/vertx/vertx-codegen/3.5.1-SNAPSHOT/vertx-codegen-3.5.1-20180118.074517-10-tck-sources.jar:/home/tsegismont/mavenrepo/io/vertx/vertx-core/3.5.1-SNAPSHOT/vertx-core-3.5.1-20180118.075439-95-tests.jar:/home/tsegismont/Projets/vert-x3/vertx-rx/rx-java/target/classes:/home/tsegismont/mavenrepo/io/reactivex/rxjava/1.3.2/rxjava-1.3.2.jar:/home/tsegismont/Projets/vert-x3/vertx-rx/rx-java/target/test-classes:/home/tsegismont/mavenrepo/junit/junit/4.12/junit-4.12.jar:/home/tsegismont/mavenrepo/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar:/home/tsegismont/mavenrepo/com/fasterxml/jackson/dataformat/jackson-dataformat-yaml/2.9.0/jackson-dataformat-yaml-2.9.0.jar:/home/tsegismont/mavenrepo/org/yaml/snakeyaml/1.17/snakeyaml-1.17.jar com.intellij.rt.execution.junit.JUnitStarter -ideVersion5 -junit4 io.vertx.reactivex.test.ReadStreamSubscriberBugTest
*** Iteration 1/100 of test
*** Iteration 2/100 of test
*** Iteration 3/100 of test
*** Iteration 4/100 of test
*** Iteration 5/100 of test
*** Iteration 6/100 of test
*** Iteration 7/100 of test

Content differs: arrays first differed at element [307200]; 
Expected :21
Actual   :87
 <Click to see difference>


	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:55)
	at org.junit.Assert.internalArrayEquals(Assert.java:532)
	at org.junit.Assert.assertArrayEquals(Assert.java:341)
	at io.vertx.reactivex.test.ReadStreamSubscriberBugTest.httpRequestToFile(ReadStreamSubscriberBugTest.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at io.vertx.test.core.RepeatRule$RepeatStatement.evaluate(RepeatRule.java:37)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.AssertionError: expected:<21> but was:<87>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at org.junit.internal.ExactComparisonCriteria.assertElementsEqual(ExactComparisonCriteria.java:8)
	at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:53)
	... 30 more


Process finished with exit code 255
```

**Comment by tsegismont** [comment]
I found this bug while trying to use `ReadStreamSubsriber` together with `Pump` to provide a WriteStream/Observer adapter (#115)

**Comment by tsegismont** [comment]
Closing invalid: I had forgotten to pause the `ReadStream`, so values would be emitted before the `Pump` was setup.
