### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-rx#158]
likely due to test:

```
Starting test: SchedulerTest#testPeriodicRescheduleAfterActionBlocking 
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at io.vertx.test.core.AsyncTestBase.fail(AsyncTestBase.java:408)
	at io.vertx.reactivex.test.SchedulerTest.lambda$testPeriodicRescheduleAfterActionBlocking$36(SchedulerTest.java:324)
	at io.vertx.reactivex.ContextScheduler$ContextWorker$TimedAction.run(ContextScheduler.java:184)
	at io.vertx.reactivex.ContextScheduler$ContextWorker$TimedAction.lambda$execute$1(ContextScheduler.java:169)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:265)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by tsegismont** [comment]
Closed via 0089855
