### ISSUE TITLE
Pause does not work, Rx semantics are ignored

### ISSUE THREAD

**Issue by dave-fl** [vert-x3/vertx-rx#187]
It does not appear that Pause has any impact at all on whether or not a stream is paused.

In the example, the Flowable chain will perform two read request on the webclient prior to reading the inbound stream and when the stream is read an error is produced that the stream has already been read.

Using version 3.7.0.

[Reproducer](https://github.com/dave-fl/ignore-pause/blob/master/src/main/java/com/example/verticles/IgnorePause.java)

	java.lang.IllegalStateException: Request has already been read
		at io.vertx.core.http.impl.HttpServerRequestImpl.checkEnded(HttpServerRequestImpl.java:607)
		at io.vertx.core.http.impl.HttpServerRequestImpl.endHandler(HttpServerRequestImpl.java:364)
		at io.vertx.ext.web.impl.HttpServerRequestWrapper.endHandler(HttpServerRequestWrapper.java:64)
		at io.vertx.ext.web.impl.HttpServerRequestWrapper.endHandler(HttpServerRequestWrapper.java:16)
		at io.vertx.reactivex.impl.FlowableReadStream.subscribeActual(FlowableReadStream.java:74)
		at io.reactivex.Flowable.subscribe(Flowable.java:14805)
		at io.reactivex.Flowable.subscribe(Flowable.java:14752)
		at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
		at io.reactivex.internal.subscriptions.DeferredScalarSubscription.complete(DeferredScalarSubscription.java:132)
		at io.reactivex.internal.operators.single.SingleToFlowable$SingleToFlowableObserver.onSuccess(SingleToFlowable.java:62)
		at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:52)
		at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:586)
		at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:583)
		at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:285)
		at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:272)
		at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:250)
		at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
		at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
		at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:247)
		at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:257)
		at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:218)
		at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:341)
		at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
		at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
		at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
		at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495)
		at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.lang.Thread.run(Thread.java:748)

**Comment by dave-fl** [comment]
This fails as well and it is only Rx.  Is it safe to say that one must always subscribe to the request stream as soon as possible.

		httpServer.requestStream().toFlowable().subscribe(serverRequest -> {
		webClient.getAbs(url).rxSend().toFlowable().flatMap(bufferHttpResponse -> {
			logger.info(bufferHttpResponse.bodyAsString());
			return webClient.getAbs(url).rxSend().toFlowable().flatMap(bufferHttpResponse1 -> {
				logger.info(bufferHttpResponse.bodyAsString());
				return serverRequest.toFlowable();
			});
		}).subscribe(buffer -> {
			serverRequest.response().write(buffer);
		}, throwable -> {
			logger.error("Error", throwable);
			serverRequest.response().setStatusCode(500);
			serverRequest.response().end();
		}, () -> {
			serverRequest.response().setStatusCode(200);
			serverRequest.response().end();
		});
	});

This works.  Stream first, order here matters.

	httpServer.requestStream().toFlowable().subscribe(serverRequest -> {
		serverRequest.response().setChunked(true);
		serverRequest.toFlowable().flatMap(buffer -> webClient.getAbs(url).rxSend().toFlowable().flatMap(bufferHttpResponse -> {
			logger.info(bufferHttpResponse.bodyAsString());
			return webClient.getAbs(url).rxSend().toFlowable().flatMap(bufferHttpResponse1 -> {
				logger.info(bufferHttpResponse.bodyAsString());
				return Flowable.just(buffer);
			});
		}))
				.subscribe(buffer -> {
					serverRequest.response().write(buffer);
				}, throwable -> {
					logger.error("Error", throwable);
					serverRequest.response().setStatusCode(500);
					serverRequest.response().end();
				}, () -> {
					serverRequest.response().setStatusCode(200);
					serverRequest.response().end();
				});

	});

**Comment by vietj** [comment]
can you test your reproducer by removing : `serverRequest.resume()` I believe it should work

**Comment by dave-fl** [comment]
@vietj In my second post above I do that, same result.

**Comment by vietj** [comment]
can you provide a full reproducer project so I understand what is going on ?

**Comment by dave-fl** [comment]
@vietj Is there something missing with the project I provided in the link above? It is a full reproducer.

**Comment by dave-fl** [comment]
@vietj Assuming that you should expect this to still use pause but otherwise not have to use resume.  You can consider this closed by 3.7.1-SNAPSHOT.

**Comment by vietj** [comment]
right I forgot to close it
