### ISSUE TITLE
ContextScheduler should handle IllegalStateException thrown by setTimer when Vert.x is closed

### ISSUE THREAD

**Issue by vietj** [vert-x3/vertx-rx#241]
```
java.lang.IllegalStateException
	at io.vertx.core.impl.CloseHooks.add(CloseHooks.java:48)
	at io.vertx.core.impl.ContextImpl.addCloseHook(ContextImpl.java:108)
	at io.vertx.core.impl.EventLoopContext.addCloseHook(EventLoopContext.java:24)
	at io.vertx.core.impl.VertxImpl.scheduleTimeout(VertxImpl.java:517)
	at io.vertx.core.impl.VertxImpl.setTimer(VertxImpl.java:367)
	at io.vertx.reactivex.ContextScheduler$ContextWorker$TimedAction.schedule(ContextScheduler.java:152)
	at io.vertx.reactivex.ContextScheduler$ContextWorker$TimedAction.access$100(ContextScheduler.java:135)
	at io.vertx.reactivex.ContextScheduler$ContextWorker.schedule(ContextScheduler.java:109)
	at io.reactivex.internal.operators.flowable.FlowableDelay$DelaySubscriber.onNext(FlowableDelay.java:81)
```

**Comment by vietj** [comment]
Actually this really be properly handled because RX seems to propagate the failure synchronously to the subscriber and the scheduler interface does not allow error reporting. So it should be left as is.

cc @jponge
