### ISSUE TITLE
How to run Testcontainer Tests?

### ISSUE THREAD

**Issue by AugustNagro** [vert-x3/vertx-rx#251]
I cloned the repo and ran `mvn clean package`. The build failed with

```
io.vertx.reactivex.sqlclient.SqlClientTest  Time elapsed: 30.349 sec  <<< ERROR!
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.lambda$getFirstValidStrategy$7(DockerClientProviderStrategy.java:215)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:207)
	at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:136)
	at org.testcontainers.DockerClientFactory.client(DockerClientFactory.java:178)
	at org.testcontainers.LazyDockerClient.getDockerClient(LazyDockerClient.java:14)
	at org.testcontainers.LazyDockerClient.authConfig(LazyDockerClient.java:12)
	at org.testcontainers.containers.GenericContainer.start(GenericContainer.java:310)
	at org.testcontainers.containers.GenericContainer.starting(GenericContainer.java:1029)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:29)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

```

I have 0 knowledge about Docker or Testcontainers. I have docker installed and the hello-world docker example runs. What do I need to do?

**Comment by tsegismont** [comment]
First, check the minimum requirements https://www.testcontainers.org/supported_docker_environment/

Then, the snippet above says `Please see logs and check configuration`
Do you have anything else in the build log that could help troubleshooting?

**Comment by AugustNagro** [comment]
@tsegismont 

I did follow that page, as well as the official docker tutorial. Unfortunately, the Testcontainer doc and error message lacks any detail. It tells me to "Please see logs and check configuration", but I see no logs produced.

Can I ask, what steps did you take to install Testcontainers/docker to run these tests? It would be nice if the README had some documentation, since clearly `mvn clean test` does not work without proper setup.

**Comment by AugustNagro** [comment]
Looks like Docker does not work well on Fedora 33 

https://www.reddit.com/r/Fedora/comments/jos0sb/issues_installing_docker_on_fedora_33/

I will manually disable those tests.

**Comment by AugustNagro** [comment]
Podman (the 'Fedora version') is not supported by Testcontainers: https://github.com/testcontainers/testcontainers-java/issues/2088

**Comment by tsegismont** [comment]
Thanks for lettings us know the cause of the issue.
